print("jangan caper")
print("hai ganteng")
print("be yourself")
print("nice try")
print("overthingking tiap malem")
print("ngga cantik")
print("insecure")
print("gausah so asik")
print("selamat pagi")
print("you know lah")